
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.2
 * Query Engine version: 94a226be1cf2967af2541cca5529f0f7ba866919
 */
Prisma.prismaVersion = {
  client: "7.4.2",
  engine: "94a226be1cf2967af2541cca5529f0f7ba866919"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  email: 'email',
  password: 'password',
  fullName: 'fullName',
  role: 'role',
  profilePhoto: 'profilePhoto',
  phone: 'phone',
  major: 'major',
  classOf: 'classOf',
  status: 'status',
  jobTitle: 'jobTitle',
  journeyRegistrationCompleted: 'journeyRegistrationCompleted',
  journeyTicketGenerated: 'journeyTicketGenerated',
  journeySeatsBooked: 'journeySeatsBooked',
  journeyGownCollected: 'journeyGownCollected',
  journeyPaymentCompleted: 'journeyPaymentCompleted',
  journeyCurrentStep: 'journeyCurrentStep',
  resetPasswordToken: 'resetPasswordToken',
  resetPasswordExpire: 'resetPasswordExpire',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  category: 'category',
  coverImage: 'coverImage',
  publishedById: 'publishedById',
  targetAudience: 'targetAudience',
  isPublished: 'isPublished',
  publishDate: 'publishDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChatMessageScalarFieldEnum = {
  id: 'id',
  senderId: 'senderId',
  receiverId: 'receiverId',
  senderRole: 'senderRole',
  message: 'message',
  attachments: 'attachments',
  isRead: 'isRead',
  roomId: 'roomId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GownCollectionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  registrationId: 'registrationId',
  size: 'size',
  collectionDate: 'collectionDate',
  scheduledDate: 'scheduledDate',
  returnDate: 'returnDate',
  status: 'status',
  depositPaid: 'depositPaid',
  depositAmount: 'depositAmount',
  notes: 'notes',
  collectionLocation: 'collectionLocation',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  message: 'message',
  type: 'type',
  relatedId: 'relatedId',
  onModel: 'onModel',
  isRead: 'isRead',
  link: 'link',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  amount: 'amount',
  paymentType: 'paymentType',
  paymentMethod: 'paymentMethod',
  status: 'status',
  transactionId: 'transactionId',
  receiptUrl: 'receiptUrl',
  items: 'items',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PhotoGalleryScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  imageUrl: 'imageUrl',
  uploadedById: 'uploadedById',
  tags: 'tags',
  ceremonyDate: 'ceremonyDate',
  likes: 'likes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  summary: 'summary',
  content: 'content',
  coverImage: 'coverImage',
  authorId: 'authorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProcessionQueueScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  queueNumber: 'queueNumber',
  major: 'major',
  status: 'status',
  callTime: 'callTime',
  completedTime: 'completedTime',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RegistrationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  ceremonyDate: 'ceremonyDate',
  gownSize: 'gownSize',
  gownCollected: 'gownCollected',
  gownCollectionTime: 'gownCollectionTime',
  attendanceConfirmed: 'attendanceConfirmed',
  checkedInById: 'checkedInById',
  checkedInAt: 'checkedInAt',
  registrationStatus: 'registrationStatus',
  specialRequirements: 'specialRequirements',
  specialNeeds: 'specialNeeds',
  guestCount: 'guestCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SeatBookingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  seatNumber: 'seatNumber',
  seatType: 'seatType',
  guestName: 'guestName',
  guestRelation: 'guestRelation',
  guestPhone: 'guestPhone',
  status: 'status',
  bookingDate: 'bookingDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SystemSettingsScalarFieldEnum = {
  id: 'id',
  ceremonyDate: 'ceremonyDate',
  registrationDeadline: 'registrationDeadline',
  maxGuestPerStudent: 'maxGuestPerStudent',
  gownCollectionStartDate: 'gownCollectionStartDate',
  gownCollectionEndDate: 'gownCollectionEndDate',
  venueCapacity: 'venueCapacity',
  isRegistrationOpen: 'isRegistrationOpen',
  ceremonyLocation: 'ceremonyLocation',
  ceremonyMapLink: 'ceremonyMapLink',
  rehearsalDate: 'rehearsalDate',
  rehearsalLocation: 'rehearsalLocation',
  rehearsalMapLink: 'rehearsalMapLink',
  gownCollectionLocation: 'gownCollectionLocation',
  gownCollectionMapLink: 'gownCollectionMapLink',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TicketScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  ticketType: 'ticketType',
  qrCode: 'qrCode',
  ticketNumber: 'ticketNumber',
  isScanned: 'isScanned',
  scannedAt: 'scannedAt',
  scannedById: 'scannedById',
  seatNumber: 'seatNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  student: 'student',
  staff: 'staff',
  admin: 'admin',
  mc: 'mc'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  active: 'active',
  inactive: 'inactive',
  suspended: 'suspended'
};

exports.AnnouncementCategory = exports.$Enums.AnnouncementCategory = {
  urgent: 'urgent',
  updates: 'updates',
  general: 'general'
};

exports.TargetAudience = exports.$Enums.TargetAudience = {
  student: 'student',
  staff: 'staff',
  admin: 'admin',
  mc: 'mc',
  all: 'all'
};

exports.GownSize = exports.$Enums.GownSize = {
  XS: 'XS',
  S: 'S',
  M: 'M',
  L: 'L',
  XL: 'XL',
  XXL: 'XXL',
  XXXL: 'XXXL'
};

exports.GownCollectionStatus = exports.$Enums.GownCollectionStatus = {
  pending: 'pending',
  scheduled: 'scheduled',
  collected: 'collected',
  returned: 'returned'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  info: 'info',
  urgent: 'urgent',
  warning: 'warning',
  success: 'success',
  system: 'system',
  registrationUpdate: 'registrationUpdate',
  ticketScan: 'ticketScan',
  gownStatus: 'gownStatus'
};

exports.NotificationModel = exports.$Enums.NotificationModel = {
  Registration: 'Registration',
  Ticket: 'Ticket',
  GownCollection: 'GownCollection',
  User: 'User'
};

exports.PaymentType = exports.$Enums.PaymentType = {
  gown_rental: 'gown_rental',
  photo_package: 'photo_package',
  additional_guest: 'additional_guest',
  graduation_package: 'graduation_package',
  other: 'other'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  bank_transfer: 'bank_transfer',
  cash: 'cash',
  online: 'online',
  qr: 'qr',
  card: 'card'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
  refunded: 'refunded'
};

exports.ProcessionQueueStatus = exports.$Enums.ProcessionQueueStatus = {
  waiting: 'waiting',
  ready: 'ready',
  on_stage: 'on_stage',
  completed: 'completed'
};

exports.RegistrationStatus = exports.$Enums.RegistrationStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  cancelled: 'cancelled'
};

exports.TicketType = exports.$Enums.TicketType = {
  student: 'student',
  guest: 'guest'
};

exports.GuestRelation = exports.$Enums.GuestRelation = {
  parent: 'parent',
  sibling: 'sibling',
  friend: 'friend',
  other: 'other'
};

exports.SeatBookingStatus = exports.$Enums.SeatBookingStatus = {
  booked: 'booked',
  confirmed: 'confirmed',
  cancelled: 'cancelled'
};

exports.Prisma.ModelName = {
  User: 'User',
  Announcement: 'Announcement',
  ChatMessage: 'ChatMessage',
  GownCollection: 'GownCollection',
  Notification: 'Notification',
  Payment: 'Payment',
  PhotoGallery: 'PhotoGallery',
  Post: 'Post',
  ProcessionQueue: 'ProcessionQueue',
  Registration: 'Registration',
  SeatBooking: 'SeatBooking',
  SystemSettings: 'SystemSettings',
  Ticket: 'Ticket'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
